# Generated by Django 5.0.2 on 2024-02-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_breakdow_exam_breakdow_exam_exammodule_exam_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammodule',
            old_name='user',
            new_name='exam',
        ),
    ]
