# Generated by Django 5.0.2 on 2024-03-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_options_alter_breakdow_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='carrer',
            new_name='career',
        ),
    ]
